### ISSUE TITLE
Actividad :Cuadro comparativo

### ISSUE THREAD

**Issue by Abisaylopez** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Abisaylopez#1]
[Tipos de TEXTOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Abisaylopez/files/9630379/Tipos.de.TEXTOS.pdf)

Alumno:Abisay López Mendoza 1bs

**Comment by AmeliReyesHernandez** [comment]
17.6 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
